"use strict";
const select=document.querySelector('#camera'),video=document.querySelector('#program'),empty=document.querySelector('#empty'),status=document.querySelector('#status'),graphic=document.querySelector('#graphic');
const consoleId=`broadcast-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;
let socket,peer,devices=[];
function send(deviceId,signal){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'webrtc_signal',device_id:deviceId,signal}));}
function closePeer(){peer?.close();peer=null;video.srcObject=null;empty.hidden=false;}
async function useCamera(id){closePeer();if(!id)return;localStorage.setItem('broadcast_camera',id);const chosen=devices.find(item=>item.device_id===id);status.textContent=`Connecting ${chosen?.name||'camera'}…`;peer=new RTCPeerConnection({iceServers:[]});peer.addTransceiver('video',{direction:'recvonly'});peer.addTransceiver('audio',{direction:'recvonly'});peer.addEventListener('track',event=>{video.srcObject=event.streams[0];empty.hidden=true;status.textContent=`LIVE · ${chosen?.name||'camera'}`;});peer.addEventListener('icecandidate',event=>{if(event.candidate)send(id,{candidate:event.candidate.toJSON()});});peer.addEventListener('connectionstatechange',()=>{if(['failed','disconnected'].includes(peer?.connectionState)){status.textContent='Camera link interrupted';empty.hidden=false;}});const offer=await peer.createOffer();await peer.setLocalDescription(offer);send(id,{description:peer.localDescription});}
function updateDevices(next){devices=next;const wanted=select.value||localStorage.getItem('broadcast_camera')||devices.find(item=>item.role==='UMPIRE_POV')?.device_id||devices[0]?.device_id||'';select.replaceChildren(...(devices.length?devices.map(item=>{const option=document.createElement('option');option.value=item.device_id;option.textContent=`${item.name} · ${item.role.replaceAll('_',' ')}`;return option;}):[Object.assign(document.createElement('option'),{value:'',textContent:'Waiting for cameras…'})]));select.value=devices.some(item=>item.device_id===wanted)?wanted:(devices[0]?.device_id||'');if(select.value&&(!peer||video.srcObject===null))useCamera(select.value);if(!select.value){closePeer();status.textContent='No connected cameras';}}
function connect(){socket=new WebSocket(`${window.DRS.websocketUrl('/ws/umpire')}?console_id=${encodeURIComponent(consoleId)}`);socket.onmessage=async event=>{const message=JSON.parse(event.data);if(message.type==='devices')updateDevices(message.devices);if(message.type==='webrtc_signal'&&message.device_id===select.value){if(message.signal.description)await peer?.setRemoteDescription(message.signal.description);if(message.signal.candidate)await peer?.addIceCandidate(message.signal.candidate);}};socket.onclose=()=>{closePeer();status.textContent='Server link lost · retrying';setTimeout(connect,1500);};}
select.addEventListener('change',()=>useCamera(select.value));document.querySelector('#showGraphic').addEventListener('change',event=>graphic.hidden=!event.target.checked);document.querySelector('#mute').addEventListener('click',event=>{video.muted=!video.muted;event.target.textContent=video.muted?'Enable camera audio':'Mute camera audio';});window.addEventListener('beforeunload',closePeer);connect();
